FROM node:12-alpine as builder

ENV HUGO_VERSION 0.67.0
ENV HUGO_BINARY hugo_${HUGO_VERSION}_Linux-64bit.tar.gz

RUN set -x && \
  apk add --update wget ca-certificates && \
  wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_BINARY} && \
  tar xzf ${HUGO_BINARY} && \
  rm -r ${HUGO_BINARY} && \
  mv hugo /usr/bin && \
  apk del wget ca-certificates && \
  rm /var/cache/apk/*

WORKDIR /var/www/website

COPY . .

ENV NODE_ENV=production

RUN npm install

RUN npm install -g gulp

RUN gulp

RUN hugo -d ./public

# gulp critical

FROM alpine:latest

WORKDIR /var/www/website

COPY --from=builder /var/www/website/public /var/www/website
